application: k16-8888
version: 1
runtime: python
api_version: 1

default_expiration: 7d  # Good for images.

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /static/(css/.*|js/.*)
  static_files: static/\1
  upload: static/(css/.*|js/.*)
  expiration: 1h  # Shorter expiration

- url: /static
  static_dir: static

- url: /content
  static_dir: content

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /.*
  script: main.py

# inbound_services:
# - xmpp_message
# - mail
