application: pythonshell1
version: 1a
runtime: python
api_version: 1

handlers:

- url: /static/(css/.*|js/.*)
  static_files: static/\1
  upload: static/(css/.*|js/.*)
  expiration: 1h  # Shorter expiration

- url: /.*
  script: rint.py
